package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"djong-reader-engine/graph/model"
	"djong-reader-engine/graphqlutils"
	"fmt"
	"log"
	"time"
)

// MstBooking is the resolver for the mstBooking field.
func (r *queryResolver) MstBooking(ctx context.Context, id string) (*model.Booking, error) {
	panic(fmt.Errorf("not implemented: MstBooking - mstBooking"))
}

// MstBookings is the resolver for the mstBookings field.
func (r *queryResolver) MstBookings(ctx context.Context, first *int32, after *string, orderBy *model.BookingOrderByInput) (*model.BookingConnection, error) {
	graphqlutils.RequestLogger(ctx, "Query MstBookings")

	var limit int32
	if first != nil {
		limit = *first
	} else {
		limit = 10 // default of limit
	}

	// Initialize sorting parameters
	sortField := "created_at"
	sortDirection := "DESC"

	// Update sorting parameters based on orderBy input
	if orderBy != nil {
		if orderBy.CreatedAt != nil {
			sortField = "created_at"
			sortDirection = string(*orderBy.CreatedAt)
		}

		// Add additional fields as needed
	}

	var cursor int32
	if after != nil {
		// Parse cursor from string to int32
		var parsedCursor int32
		_, err := fmt.Sscanf(*after, "%d", &parsedCursor)
		if err != nil {
			log.Println("Error parsing cursor: ", err)
			cursor = 0
		} else {
			cursor = parsedCursor
		}
	} else {
		cursor = 0
	}

	query := fmt.Sprintf(`
		SELECT id, booking_code, booking_date, created_at, created_by, updated_at, updated_by, is_active
		FROM djong_phinisi.mst_booking
		ORDER BY %s %s
		OFFSET $1
        LIMIT $2
	`, sortField, sortDirection)

	rows, err := r.DB.Query(ctx, query, cursor, limit)
	if err != nil {
		log.Println("Error fetching bookings: ", err)
		return nil, err
	}

	defer rows.Close()

	var bookings []*model.Booking
	var lastCursor string
	for rows.Next() {
		var bk model.Booking
		var createdAt *time.Time
		var bookingDate *time.Time

		if err := rows.Scan(
			&bk.ID, &bk.BookingCode, &bookingDate, &createdAt, &bk.CreatedBy,
			&bk.UpdatedAt, &bk.UpdatedBy, &bk.IsActive,
		); err != nil {
			log.Println("Error scanning Booking: ", err)
			continue
		}

		// ✅ Convert time.Time to model.Time
		if ts := model.TimeFromPtr(createdAt); ts != nil {
			bk.CreatedAt = ts.ToTime()
		}

		bookings = append(bookings, &bk)
		lastCursor = bk.ID
	}

	bookingPageInfo := &model.BookingPageInfo{
		EndCursor:   &lastCursor,
		HasNextPage: len(bookings) == int(limit),
	}

	edges := make([]*model.BookingEdge, len(bookings))
	for i, bk := range bookings {
		edges[i] = &model.BookingEdge{
			Cursor: bk.ID,
			Node:   bk,
		}
	}
	var response = &model.BookingConnection{
		Edges:    edges,
		PageInfo: bookingPageInfo,
	}

	graphqlutils.ResponseLogger(response)

	return response, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
