package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"djong-reader-engine/graph/model"
	"djong-reader-engine/graphqlutils"
	"fmt"
	"log"
	"time"
)

// Lead is the resolver for the lead field.
func (r *queryResolver) Lead(ctx context.Context, id string) (*model.Lead, error) {
	panic(fmt.Errorf("not implemented: Lead - lead"))
}

// Leads is the resolver for the leads field.
func (r *queryResolver) Leads(ctx context.Context, first *int32, after *int32, orderBy *model.LeadOrderByInput) (*model.LeadConnection, error) {
	graphqlutils.RequestLogger(ctx, "Query Leads")

	var limit int32
	if first != nil {
		limit = *first
	} else {
		limit = 10 // default of limit
	}

	// Initialize sorting parameters
	sortField := "created_at"
	sortDirection := "DESC"

	// Update sorting parameters based on orderBy input
	if orderBy != nil {
		if orderBy.CreatedAt != nil {
			sortField = "created_at"
			sortDirection = string(*orderBy.CreatedAt)
		}

		// Add additional fields as needed
	}

	var cursor int32
	if after != nil {
		cursor = *after
	} else {
		cursor = 0
	}

	query := fmt.Sprintf(`
		SELECT mld.id , mld.sp_stage_id , mld.comment , mld.created_at , mld.created_by , mld.updated_at , mld.updated_by , mld.is_active , mld.sales_pipeline_id 
		FROM mst_lead mld
		ORDER BY %s %s
		OFFSET $1
        LIMIT $2
	`, sortField, sortDirection)

	rows, err := r.DB.Query(ctx, query, cursor, limit)
	if err != nil {
		log.Println("Error fetching leads: ", err)
		return nil, err
	}

	defer rows.Close()

	var leads []*model.Lead
	var lastCursor string
	for rows.Next() {
		var ld model.Lead
		var createdAt *time.Time

		if err := rows.Scan(
			&ld.ID, &ld.SpStageID, &ld.Comment, &createdAt, &ld.CreatedBy,
			&ld.UpdatedAt, &ld.UpdatedBy, &ld.IsActive,
			&ld.SalesPipelineID,
		); err != nil {
			log.Println("Error scaning Leads: ", err)
			continue
		}

		// ✅ Convert time.Time to model.Time
		if ts := model.TimeFromPtr(createdAt); ts != nil {
			ld.CreatedAt = time.Time(*ts)
		}

		leads = append(leads, &ld)
		lastCursor = ld.ID
	}

	leadPageInfo := &model.LeadPageInfo{
		EndCursor:   &lastCursor,
		HasNextPage: len(leads) == int(limit),
	}

	edges := make([]*model.LeadEdge, len(leads))
	for i, ld := range leads {
		edges[i] = &model.LeadEdge{
			Cursor: ld.ID,
			Node:   ld,
		}
	}
	var response = &model.LeadConnection{
		Edges:    edges,
		PageInfo: leadPageInfo,
	}

	graphqlutils.ResponseLogger(response)

	return response, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
