package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"djong-reader-engine/graph/model"
	"djong-reader-engine/graphqlutils"
	"fmt"
	"log"
	"time"
)

// JukungPricingTier is the resolver for the jukungPricingTier field.
func (r *queryResolver) JukungPricingTier(ctx context.Context, id string) (*model.PricingTier, error) {
	panic(fmt.Errorf("not implemented: JukungPricingTier - jukungPricingTier"))
}

// JukungPricingTiers is the resolver for the jukungPricingTiers field.
func (r *queryResolver) JukungPricingTiers(ctx context.Context, first *int32, after *string, orderBy *model.PricingTierOrderByInput) (*model.PricingTierConnection, error) {
	graphqlutils.RequestLogger(ctx, "Query JukungPricingTiers")

	var limit int32
	if first != nil {
		limit = *first
	} else {
		limit = 10 // default of limit
	}

	// Initialize sorting parameters
	sortField := "created_at"
	sortDirection := "DESC"

	// Update sorting parameters based on orderBy input
	if orderBy != nil {
		if orderBy.CreatedAt != nil {
			sortField = "created_at"
			sortDirection = string(*orderBy.CreatedAt)
		}

		// Add additional fields as needed
	}

	var cursor int32
	if after != nil {
		// Parse cursor from string to int32
		var parsedCursor int32
		_, err := fmt.Sscanf(*after, "%d", &parsedCursor)
		if err != nil {
			log.Println("Error parsing cursor: ", err)
			cursor = 0
		} else {
			cursor = parsedCursor
		}
	} else {
		cursor = 0
	}

	query := fmt.Sprintf(`
		SELECT id, product_id, pr_valid_min, pr_valid_max, created_at, created_by, updated_at, updated_by, is_active, rate, currency_id
		FROM djong_jukung.mst_pricing_tiers
		ORDER BY %s %s
		OFFSET $1
        LIMIT $2
	`, sortField, sortDirection)

	rows, err := r.DBJukung.Query(ctx, query, cursor, limit)
	if err != nil {
		log.Println("Error fetching pricing tiers: ", err)
		return nil, err
	}

	defer rows.Close()

	var pricingTiers []*model.PricingTier
	var lastCursor string
	for rows.Next() {
		var pt model.PricingTier
		var createdAt *time.Time

		if err := rows.Scan(
			&pt.ID, &pt.ProductID, &pt.PrValidMin, &pt.PrValidMax, &createdAt, &pt.CreatedBy,
			&pt.UpdatedAt, &pt.UpdatedBy, &pt.IsActive, &pt.Rate, &pt.CurrencyID,
		); err != nil {
			log.Println("Error scanning PricingTier: ", err)
			continue
		}

		// ✅ Convert time.Time to model.Time
		if ts := model.TimeFromPtr(createdAt); ts != nil {
			pt.CreatedAt = time.Time(*ts)
		}

		pricingTiers = append(pricingTiers, &pt)
		lastCursor = pt.ID
	}

	pricingTierPageInfo := &model.PricingTierPageInfo{
		EndCursor:   &lastCursor,
		HasNextPage: len(pricingTiers) == int(limit),
	}

	edges := make([]*model.PricingTierEdge, len(pricingTiers))
	for i, pt := range pricingTiers {
		edges[i] = &model.PricingTierEdge{
			Cursor: pt.ID,
			Node:   pt,
		}
	}
	var response = &model.PricingTierConnection{
		Edges:    edges,
		PageInfo: pricingTierPageInfo,
	}

	graphqlutils.ResponseLogger(response)

	return response, nil
}
