package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"djong-reader-engine/graph/model"
	"djong-reader-engine/graphqlutils"
	"fmt"
	"log"
	"time"
)

// MstProduct is the resolver for the mstProduct field.
func (r *queryResolver) MstProduct(ctx context.Context, first *int32, after *string, orderBy *model.ProductOrderByInput) (*model.ProductConnection, error) {
	graphqlutils.RequestLogger(ctx, "Query MstProduct")

	var limit int32
	if first != nil {
		limit = *first
	} else {
		limit = 10 // default of limit
	}

	// Initialize sorting parameters
	sortField := "created_at"
	sortDirection := "DESC"

	// Update sorting parameters based on orderBy input
	if orderBy != nil {
		if orderBy.CreatedAt != nil {
			sortField = "created_at"
			sortDirection = string(*orderBy.CreatedAt)
		}

		// Add additional fields as needed
	}

	var cursor int32
	if after != nil {
		// Parse cursor from string to int32
		var parsedCursor int32
		_, err := fmt.Sscanf(*after, "%d", &parsedCursor)
		if err != nil {
			log.Println("Error parsing cursor: ", err)
			cursor = 0
		} else {
			cursor = parsedCursor
		}
	} else {
		cursor = 0
	}

	query := fmt.Sprintf(`
		SELECT id, destination_id, description, total_duration, created_by, created_at, updated_by, updated_at, is_active
		FROM djong_jukung.mst_product
		ORDER BY %s %s
		OFFSET $1
        LIMIT $2
	`, sortField, sortDirection)

	rows, err := r.DBJukung.Query(ctx, query, cursor, limit)
	if err != nil {
		log.Println("Error fetching products: ", err)
		return nil, err
	}

	defer rows.Close()

	var products []*model.Product
	var lastCursor string
	for rows.Next() {
		var p model.Product
		var createdAt *time.Time

		if err := rows.Scan(
			&p.ID, &p.DestinationID, &p.Description, &p.TotalDuration, &p.CreatedBy,
			&createdAt, &p.UpdatedBy, &p.UpdatedAt, &p.IsActive,
		); err != nil {
			log.Println("Error scanning Product: ", err)
			continue
		}

		// ✅ Convert time.Time to model.Time
		if ts := model.TimeFromPtr(createdAt); ts != nil {
			p.CreatedAt = time.Time(*ts)
		}

		products = append(products, &p)
		lastCursor = p.ID
	}

	productPageInfo := &model.ProductPageInfo{
		EndCursor:   &lastCursor,
		HasNextPage: len(products) == int(limit),
	}

	edges := make([]*model.ProductEdge, len(products))
	for i, p := range products {
		edges[i] = &model.ProductEdge{
			Cursor: p.ID,
			Node:   p,
		}
	}
	var response = &model.ProductConnection{
		Edges:    edges,
		PageInfo: productPageInfo,
	}

	graphqlutils.ResponseLogger(response)

	return response, nil
}
