package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"djong-reader-engine/graph/model"
	"djong-reader-engine/graphqlutils"
	"fmt"
	"log"
	"time"
)

// JukungRefDestination is the resolver for the jukungRefDestination field.
func (r *queryResolver) JukungRefDestination(ctx context.Context, id string) (*model.RefDestination, error) {
	panic(fmt.Errorf("not implemented: JukungRefDestination - jukungRefDestination"))
}

// JukungRefDestinations is the resolver for the jukungRefDestinations field.
func (r *queryResolver) JukungRefDestinations(ctx context.Context, first *int32, after *string, orderBy *model.RefDestinationOrderByInput) (*model.RefDestinationConnection, error) {
	graphqlutils.RequestLogger(ctx, "Query JukungRefDestinations")

	var limit int32
	if first != nil {
		limit = *first
	} else {
		limit = 10 // default of limit
	}

	// Initialize sorting parameters
	sortField := "created_at"
	sortDirection := "DESC"

	// Update sorting parameters based on orderBy input
	if orderBy != nil {
		if orderBy.CreatedAt != nil {
			sortField = "created_at"
			sortDirection = string(*orderBy.CreatedAt)
		}

		// Add additional fields as needed
	}

	var cursor int32
	if after != nil {
		// Parse cursor from string to int32
		var parsedCursor int32
		_, err := fmt.Sscanf(*after, "%d", &parsedCursor)
		if err != nil {
			log.Println("Error parsing cursor: ", err)
			cursor = 0
		} else {
			cursor = parsedCursor
		}
	} else {
		cursor = 0
	}

	query := fmt.Sprintf(`
		SELECT id, destination_name, is_combination, created_at, created_by, updated_at, updated_by, is_active
		FROM djong_jukung.ref_destination
		ORDER BY %s %s
		OFFSET $1
        LIMIT $2
	`, sortField, sortDirection)

	rows, err := r.DBJukung.Query(ctx, query, cursor, limit)
	if err != nil {
		log.Println("Error fetching ref destinations: ", err)
		return nil, err
	}

	defer rows.Close()

	var refDestinations []*model.RefDestination
	var lastCursor string
	for rows.Next() {
		var rd model.RefDestination
		var createdAt *time.Time

		if err := rows.Scan(
			&rd.ID, &rd.DestinationName, &rd.IsCombination, &createdAt, &rd.CreatedBy,
			&rd.UpdatedAt, &rd.UpdatedBy, &rd.IsActive,
		); err != nil {
			log.Println("Error scanning RefDestination: ", err)
			continue
		}

		// ✅ Convert time.Time to model.Time
		if ts := model.TimeFromPtr(createdAt); ts != nil {
			rd.CreatedAt = time.Time(*ts)
		}

		refDestinations = append(refDestinations, &rd)
		lastCursor = rd.ID
	}

	refDestinationPageInfo := &model.RefDestinationPageInfo{
		EndCursor:   &lastCursor,
		HasNextPage: len(refDestinations) == int(limit),
	}

	edges := make([]*model.RefDestinationEdge, len(refDestinations))
	for i, rd := range refDestinations {
		edges[i] = &model.RefDestinationEdge{
			Cursor: rd.ID,
			Node:   rd,
		}
	}
	var response = &model.RefDestinationConnection{
		Edges:    edges,
		PageInfo: refDestinationPageInfo,
	}

	graphqlutils.ResponseLogger(response)

	return response, nil
}
