// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Booking struct {
	ID          string     `json:"id"`
	BookingCode *string    `json:"bookingCode,omitempty"`
	BookingDate *time.Time `json:"bookingDate,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	CreatedBy   *string    `json:"createdBy,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy   *string    `json:"updatedBy,omitempty"`
	IsActive    bool       `json:"isActive"`
}

type BookingConnection struct {
	Edges    []*BookingEdge   `json:"edges,omitempty"`
	PageInfo *BookingPageInfo `json:"pageInfo,omitempty"`
}

type BookingEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Booking `json:"node"`
}

type BookingOrderByInput struct {
	CreatedAt *SortOrderBooking `json:"createdAt,omitempty"`
}

type BookingPageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Lead struct {
	ID              string     `json:"id"`
	SpStageID       *int32     `json:"spStageId,omitempty"`
	Comment         *string    `json:"comment,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	CreatedBy       *string    `json:"createdBy,omitempty"`
	UpdatedAt       *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy       *string    `json:"updatedBy,omitempty"`
	IsActive        bool       `json:"isActive"`
	SalesPipelineID *int32     `json:"salesPipelineId,omitempty"`
}

type LeadConnection struct {
	Edges    []*LeadEdge   `json:"edges,omitempty"`
	PageInfo *LeadPageInfo `json:"pageInfo,omitempty"`
}

type LeadEdge struct {
	Cursor string `json:"cursor"`
	Node   *Lead  `json:"node"`
}

type LeadOrderByInput struct {
	CreatedAt *SortOrderLead `json:"createdAt,omitempty"`
}

type LeadPageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PricingTier struct {
	ID         string     `json:"id"`
	ProductID  *int32     `json:"productId,omitempty"`
	PrValidMin *int32     `json:"prValidMin,omitempty"`
	PrValidMax *int32     `json:"prValidMax,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
	CreatedBy  *string    `json:"createdBy,omitempty"`
	UpdatedAt  *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy  *string    `json:"updatedBy,omitempty"`
	IsActive   bool       `json:"isActive"`
	Rate       *float64   `json:"rate,omitempty"`
	CurrencyID *int32     `json:"currencyId,omitempty"`
}

type PricingTierConnection struct {
	Edges    []*PricingTierEdge   `json:"edges,omitempty"`
	PageInfo *PricingTierPageInfo `json:"pageInfo,omitempty"`
}

type PricingTierEdge struct {
	Cursor string       `json:"cursor"`
	Node   *PricingTier `json:"node"`
}

type PricingTierOrderByInput struct {
	CreatedAt *SortOrderPricingTier `json:"createdAt,omitempty"`
}

type PricingTierPageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Query struct {
}

type SalesPipeline struct {
	ID                 string     `json:"id"`
	Value              *string    `json:"value,omitempty"`
	EstimatedCloseDate *time.Time `json:"estimatedCloseDate,omitempty"`
	PaxName            *string    `json:"paxName,omitempty"`
	PicName            *string    `json:"picName,omitempty"`
	CreatedAt          time.Time  `json:"createdAt"`
	CreatedBy          *string    `json:"createdBy,omitempty"`
	UpdatedAt          *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy          *string    `json:"updatedBy,omitempty"`
	IsActive           bool       `json:"isActive"`
}

type SalesPipelineConnection struct {
	Edges    []*SalesPipelineEdge `json:"edges,omitempty"`
	PageInfo *PageInfo            `json:"pageInfo,omitempty"`
}

type SalesPipelineEdge struct {
	Cursor string         `json:"cursor"`
	Node   *SalesPipeline `json:"node"`
}

type SalesPipelineOrderByInput struct {
	CreatedAt *SortOrderSalesPipeline `json:"createdAt,omitempty"`
}

type SortOrderBooking string

const (
	SortOrderBookingAsc  SortOrderBooking = "ASC"
	SortOrderBookingDesc SortOrderBooking = "DESC"
)

var AllSortOrderBooking = []SortOrderBooking{
	SortOrderBookingAsc,
	SortOrderBookingDesc,
}

func (e SortOrderBooking) IsValid() bool {
	switch e {
	case SortOrderBookingAsc, SortOrderBookingDesc:
		return true
	}
	return false
}

func (e SortOrderBooking) String() string {
	return string(e)
}

func (e *SortOrderBooking) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrderBooking(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrderBooking", str)
	}
	return nil
}

func (e SortOrderBooking) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortOrderLead string

const (
	SortOrderLeadAsc  SortOrderLead = "ASC"
	SortOrderLeadDesc SortOrderLead = "DESC"
)

var AllSortOrderLead = []SortOrderLead{
	SortOrderLeadAsc,
	SortOrderLeadDesc,
}

func (e SortOrderLead) IsValid() bool {
	switch e {
	case SortOrderLeadAsc, SortOrderLeadDesc:
		return true
	}
	return false
}

func (e SortOrderLead) String() string {
	return string(e)
}

func (e *SortOrderLead) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrderLead(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrderLead", str)
	}
	return nil
}

func (e SortOrderLead) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortOrderPricingTier string

const (
	SortOrderPricingTierAsc  SortOrderPricingTier = "ASC"
	SortOrderPricingTierDesc SortOrderPricingTier = "DESC"
)

var AllSortOrderPricingTier = []SortOrderPricingTier{
	SortOrderPricingTierAsc,
	SortOrderPricingTierDesc,
}

func (e SortOrderPricingTier) IsValid() bool {
	switch e {
	case SortOrderPricingTierAsc, SortOrderPricingTierDesc:
		return true
	}
	return false
}

func (e SortOrderPricingTier) String() string {
	return string(e)
}

func (e *SortOrderPricingTier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrderPricingTier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrderPricingTier", str)
	}
	return nil
}

func (e SortOrderPricingTier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortOrderSalesPipeline string

const (
	SortOrderSalesPipelineAsc  SortOrderSalesPipeline = "ASC"
	SortOrderSalesPipelineDesc SortOrderSalesPipeline = "DESC"
)

var AllSortOrderSalesPipeline = []SortOrderSalesPipeline{
	SortOrderSalesPipelineAsc,
	SortOrderSalesPipelineDesc,
}

func (e SortOrderSalesPipeline) IsValid() bool {
	switch e {
	case SortOrderSalesPipelineAsc, SortOrderSalesPipelineDesc:
		return true
	}
	return false
}

func (e SortOrderSalesPipeline) String() string {
	return string(e)
}

func (e *SortOrderSalesPipeline) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrderSalesPipeline(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrderSalesPipeline", str)
	}
	return nil
}

func (e SortOrderSalesPipeline) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
